spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: 'jdbc:mariadb://localhost/especialista_jpa?createDatabaseIfNotExist=true&serverTimezone=UTC'
    username: root
    password: my-secret-pwd
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB10Dialect
        format_sql: true