spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: 'jdbc:mariadb://localhost/especialista_jpa?createDatabaseIfNotExist=true&serverTimezone=UTC'
    username: root
    password: my-secret-pwd
